name = "skypanel"
type = "javascript"
account_id = "your_account_id"
workers_dev = true
compatibility_date = "2023-01-01"

[env.production]
name = "skypanel-production"
route = "https://your-production-domain.com/*"
zone_id = "your_zone_id"

[env.staging]
name = "skypanel-staging"
route = "https://your-staging-domain.com/*"
zone_id = "your_zone_id"
