name: skypanel
services:
- name: web
  source_dir: /
  github:
    repo: skyvps360/SkyPANEL
    branch: main
  run_command: npm start
  build_command: npm run build
  environment_slug: node-js
  instance_count: 1
  instance_size_slug: basic-xxs
  routes:
  - path: /
  envs:
  - key: NODE_ENV
    value: production
  - key: PORT
    value: "8080"
  # Add your environment variables here
  # - key: DATABASE_URL
  #   value: your_database_url
  # - key: VITE_PAYPAL_CLIENT_ID
  #   value: your_paypal_client_id
